### ISSUE TITLE
How do I set up and use kraken correctly?

### ISSUE THREAD

**Issue by NikiChr** [uber/kraken#209]
I have set up a very simple network (using containernet) that is made up of four hosts:

- r1:`44.44.12.1`
- r2:`44.44.12.2`
- r3:`44.44.13.3`
- r4:`44.44.24.4`

So first up I would like to know if my setup is correct so far.
The host **r1** is running a herd container while the other 3 hosts run an agent container, using the images created by _make install_.
When I start up the network I use the following docker-compose.yml for **r1**:
```version: "3"
services:
  routing:
    image: 172.17.0.1:5000/babeld
    privileged: true
    network_mode: "host"
    container_name: babeld
  
  herd:
    image: 172.17.0.1:5000/kraken-herd
    container_name: kraken_herd
    ports:
        #- 14001:14001 #Redis
        - 15000:15000 #Proxy
        - 15001:15001 #Origin Peer
        - 15002:15002 #Origin Server
        - 15003:15003 #Tracker
        - 15004:15004 #Build-Index
        - 15005:15005 #Proxy Server
    volumes:
        - /etc/kraken/config/origin/development.yaml:/etc/kraken/config/origin/development.yaml
        - /etc/kraken/config/tracker/development.yaml:/etc/kraken/config/tracker/development.yaml
        - /etc/kraken/config/build-index/development.yaml:/etc/kraken/config/build-index/development.yaml
        - /etc/kraken/config/proxy/development.yaml:/etc/kraken/config/proxy/development.yaml
        - /herd_param.sh:/herd_param.sh
        - /herd_start_processes.sh:/herd_start_processes.sh
    restart: always
    command: /herd_start_processes.sh
```
And the following .yml for the agent hosts **r2**, **r3**, **r4**.
```
version: "3"
services:
    routing:
        image: 172.17.0.1:5000/babeld #dm4tze/babeld/dev
        privileged: true
        network_mode: "host"
        container_name: babeld
    
    agent:
        image: 172.17.0.1:5000/kraken-agent
        restart: always
        privileged: true
        #network_mode: "host"
        container_name: kraken_agent
        ports:
            - 16000:16000 #Registry
            - 16001:16001 #Peer
            - 16002:16002 #Server
        volumes:
            - /etc/kraken/config/agent/development.yaml:/etc/kraken/config/agent/development.yaml
        command: /usr/bin/kraken-agent --config=/etc/kraken/config/agent/development.yaml --peer-ip=${IP} --peer-port=16001 --agent-server-port=16002 --agent-registry-port=16000
```
Furthermore, every file in ./etc/kraken/config/... is adjusted to contain the respective host's IP address.
The same goes for the **files agent_param.sh** and **herd_param.sh**.

- [x] Is it correct that the herd container works like a combination of a proxy, origin, tracker and build index container?
- [x] Do I need to set up/attach a backend storage or is there a registry included in any of the kraken containers?
- [x] If not can I use a docker registry for each host and run it with the _proxy_port_ for **r1** and the  _agent_registry_port_?
- [x] Is my setup sufficient for using Kraken or am I missing something?

Moreover, I tried using kraken with the nginx image as a test.
```
#using r1
docker pull nginx
docker tag nginx:latest localhost:15000/nginx:latest
docker push localhost:15000/nginx:latest

#using r2, r3, r4
docker pull 44.44.12.1:16000/nginx:latest
```
- [x] Is that the correct way to use kraken?

This however creates the following output.
```
bash-5.0# docker push localhost:15000/nginx:latest
The push refers to repository [localhost:15000/nginx]
Get http://localhost:15000/v2/: dial tcp [::1]:15000: connect: connection refused
```

- [x] Finally are there any log files besides _docker logs_ of the kraken containers?
It would be great to know how long the download of pieces and the whole image took.
As well as the information where every piece was sourced from.

**Comment by evelynl94** [comment]
> Is it correct that the herd container works like a combination of a proxy, origin, tracker and build index container?

yes

> Do I need to set up/attach a backend storage or is there a registry included in any of the kraken containers?

There is no default backend from the code, but we have testfs (also s3/hdfs/gcs) that you may be able to play with.

> If not can I use a docker registry for each host and run it with the proxy_port for r1 and the agent_registry_port?

Yes, the registry port can be the same on proxy and agent as long as they are not collocated on the same host.

> Is that the correct way to use kraken?

Yes

> Finally are there any log files besides docker logs of the kraken containers?

Logs are configurable. One example https://github.com/uber/kraken/blob/master/config/proxy/base.yaml#L50.

**Comment by NikiChr** [comment]
Thank you for the very quick response!
However I still receive an error message when I try to follow this guide [**Push And Pull Docker Images**](https://github.com/uber/kraken/blob/master/docs/ENDPOINTS.md#push-and-pull-docker-images ).
The kraken-herd container runs on **r1** and a kraken-agent container runs on **r2**, **r3** and **r4**, they are started with the docker-compose files as shown above.
When I try to push an image to the proxy, from any host, I receive the following message:
```
# docker push 44.44.12.1:15000/nginx:latest
The push refers to repository [44.44.12.1:15000/nginx]
Get https://44.44.12.1:15000/v2/: dial tcp 44.44.12.1:15000: connect: connection refused


# docker push localhost:15000/nginx:latest
The push refers to repository [localhost:15000/nginx]
Get http://localhost:15000/v2/: dial tcp [::1]:15000: connect: connection refused
```
Furthermore I whitelisted the port in the docker deamon.json.
```

```

**Comment by evelynl94** [comment]
could you verify if proxy is listening on the correct port? You can
`curl -v localhost:15055/v2/`

**Comment by NikiChr** [comment]
Thank you for the very quick response!
However I still receive an error message when I try to follow this guide [**Push And Pull Docker Images**](https://github.com/uber/kraken/blob/master/docs/ENDPOINTS.md#push-and-pull-docker-images ).
The kraken-herd container runs on **r1** and a kraken-agent container runs on **r2**, **r3** and **r4**, they are started with the docker-compose files as shown above.

I whitelisted the proxy port 15000 in the docker deamon.json.
```
{
    "registry-mirrors": ["http://172.17.0.1:5000","http://172.18.0.1:5000","http://172.17.0.1:15000","http://172.18.0.1:15000","http://127.0.0.1:5000","http://127.0.0.1:15000"],
	"insecure-registries": ["172.17.0.1:5000","172.18.0.1:5000","172.17.0.1:15000","172.18.0.1:15000","127.0.0.1:5000","127.0.0.1:15000"]
}
```
I attached a docker registry to every host running a herd-container and modified the _development.yaml_ for _build-index_ and _origin_ like the following, to include the docker registry as a backend, in this case only for **r1**.

etc/kraken/config/build-index/development.yaml
```
backends:
  - namespace: .*
    backend:
      registry_tag:
        address: 44.44.12.1:5000
        security:
          tls:
            client:
              disabled: true
```
etc/kraken/config/origin/development.yaml
```
backends:
  - namespace: .*
    backend:
      registry_blob:
        address: 44.44.12.1:5000
        security:
          tls:
            client:
              disabled: true
```
When I try to push an image to the proxy, from any host, I receive the following message:
```
# docker push 44.44.12.1:15000/nginx:latest
The push refers to repository [44.44.12.1:15000/nginx]
Get https://44.44.12.1:15000/v2/: dial tcp 44.44.12.1:15000: connect: connection refused


# docker push localhost:15000/nginx:latest
The push refers to repository [localhost:15000/nginx]
Get http://localhost:15000/v2/: dial tcp [::1]:15000: connect: connection refused
```

Moreover if I push an image directly to the registry on port 5000 and pull it from an agent via the agent_registry_port 16000 for example from the host **r2** I receive this error response:
```
# docker pull localhost:16000/nginx:latest
Error response from daemon: error parsing HTTP 403 response body: invalid character '<' looking for beginning of value: "<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n"
```


Do you know what I need to adjust to get everything to work?
Can I use the [regular docker registry ](https://hub.docker.com/_/registry) as a backend or is the "read only restriction" limiting the functionality for kraken?
