### ISSUE TITLE
Allow for conflicting namespaces: introducing backend prefixes

### ISSUE THREAD

**Issue by wk8** [uber/kraken#278]
**Is your feature request related to a problem? Please describe.**
I have 3 different backends, `a`, `b` and `c`. I'd like Kraken to provide a single registry for all three.

As I understand it, Kraken currently allows to do that as long as the image names (repos and tags) in all three backends obey to some pattern that allows them to be neatly divided into Kraken namespaces. However, for reasons outside of my control, that's not the case for me: any image name can be found in any backend.

I'd still like to be able to configure Kraken to be able to do `docker pull localhost:8081/a/my/image:1.0` (assuming the Kraken agent is listening on port 8081), and have Kraken understand that I want to pull `my/image:1.0` from backend `a`; and `docker pull localhost:8081/b/my/image:1.0` would pull `my/image:1.0` from backend `b`.

**Describe the solution you'd like**
A way to achieve that could be to add a new, optional `prefix` field in backend definitions, that Kraken would understand to be the artificial prefix that it needs to remove when talking to the underlying backend.

The example from the previous section could then be configured as:
```yml
backends:
  - namespace: '^a/.*'
    prefix: a/
    backend:
      registry_blob:
        ...

  - namespace: '^b/.*'
    prefix: b/
    backend:
      s3:
        ...

  - namespace: '^c/.*'
    prefix: c/
    backend:
      http:
        ...
```

That change would enable that new use-case while being completely seamless for existing deployments/configurations.

### I would be happy to submit a PR for this as long as maintainers pre-approve the idea.

Thanks.
